// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Diploma_Server
{
    public partial class RegressionModel
    {
        /// <summary>
        /// model input class for RegressionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(4)]
            [ColumnName(@"stars")]
            public float Stars { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"boughtInLastMonth")]
            public float BoughtInLastMonth { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Discount")]
            public float Discount { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"log_reviews")]
            public float Log_reviews { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"log_price")]
            public float Log_price { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"priceStrategy")]
            public float PriceStrategy { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"demand")]
            public float Demand { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"quality")]
            public float Quality { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"priceQuality")]
            public float PriceQuality { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for RegressionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"stars")]
            public float Stars { get; set; }

            [ColumnName(@"boughtInLastMonth")]
            public float BoughtInLastMonth { get; set; }

            [ColumnName(@"Discount")]
            public float Discount { get; set; }

            [ColumnName(@"log_reviews")]
            public float Log_reviews { get; set; }

            [ColumnName(@"log_price")]
            public float Log_price { get; set; }

            [ColumnName(@"priceStrategy")]
            public float PriceStrategy { get; set; }

            [ColumnName(@"demand")]
            public float Demand { get; set; }

            [ColumnName(@"quality")]
            public float Quality { get; set; }

            [ColumnName(@"priceQuality")]
            public float PriceQuality { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("RegressionModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
